# Generated by Django 5.0.6 on 2024-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='npn',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
